Update connection.js
haraka/Haraka pull request #2851
Opened 2020-09-30 13:41 UTC by adarshasp87

Fixes #2850 

Changes proposed in this pull request:
- skip received header stamping if its disabled in configuration
-  skip calling auth_results_clean method if its disabled in configuration

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

2020-09-30 18:43 UTC, msimerson requested changes
Please use verb prefixed imperative names for config files, as you did with hide_received_header. When you have negative post-verb naming like `disable_auth_results_clean` we can end up with obtuse and harder to reason about statements like `if (!disable_auth_results_clean) {`.

Your first variable would be better named `clean_auth_results`.

I wonder why both options are needed. If you aren't adding a Received header, then you're essentially hiding the Haraka hop in the message headers. If you're doing that, it follows that you wouldn't clean and the OAR header. Am I missing something?

The other major issue with this setting is discoverability. There's no docs included here. The only way for someone to find this knob to twiddle is by reading the source. I'm also not a fan of just adding another entry to docs/CoreConfig.pm.

@core , what do you think of consolidating this and a few other settings to `smtp.ini`? IE, something like this:

```ini
diff --git a/config/smtp.ini b/config/smtp.ini
index 042d57db..e14e4bd0 100644
--- a/config/smtp.ini
+++ b/config/smtp.ini
@@ -43,3 +43,16 @@
 ;   after this time it will hard close. 30s is usually long enough to
 ;   wait for outbound connections to finish.
 ;force_shutdown_timeout=30
+
+[headers]
+add_received=true
+clean_original_auth_results=true
+
+; replace header_hide_version
+show_haraka_version=true
+
+; replace max_header_lines
+max_lines=1000
+
+; replace max_received_count
+max_received=100
```

2020-09-30 18:45 UTC, msimerson commented on connection.js
> +            this.accumulate_data(`Received: ${this.received_line()}\r\n`);
Either use brackets or make this a single line `if` statement.

2020-09-30 18:45 UTC, msimerson commented on connection.js
> +            this.auth_results_clean();   // rename old A-R headers
same, brackets or single line.

2020-10-01 05:47 UTC, adarshasp87 commented on connection.js
> +            this.auth_results_clean();   // rename old A-R headers
Done

2020-10-01 05:52 UTC, adarshasp87 reviewed
changes are committed as per code review comments. 

@msimerson  consolidation of settings to smtp.ini is a very good idea.
Answer to your question of why both options are needed. We use Haraka SMTP to collect eml and not to route further. So it's important to get the eml in original form(to match the checksum when collected through Haraka)

2020-10-01 21:58 UTC, msimerson commented
> So it's important to get the eml in original form.

I get that. But couldn't you use just a single setting to control both? When would you want to hide the Received header and not clean the OAR header?  Or vice versa?

I'm leaving this PR with my smtp.ini question open for a few days so @core members have a chance to chime in.

2020-10-05 03:47 UTC, adarshasp87 commented
> > So it's important to get the eml in original form.
> 
> I get that. But couldn't you use just a single setting to control both? When would you want to hide the Received header and not clean the OAR header? Or vice versa?
> We don't have such use cases. Introduced two separate settings not breaking the existing functionality or causing any problems.
> I'm leaving this PR with my smtp.ini question open for a few days so @core members have a chance to chime in.

2020-11-04 04:30 UTC, adarshasp87 commented
@msimerson Any update on this PR. We are eagerly looking for this feature.
If you think consolidation of settings to smtp.ini is a good option, I will spend sometime and raise another PR.

2020-11-04 05:07 UTC, msimerson commented
If this PR instead added settings to smtp.ini, I'd have merged it already.

I was hoping another core member would comment. I really dislike the "just add another config file" pattern for settings. It's terrible for discovery (if the config file doesn't exist, the only way to discover the setting is reading the code or docs. Perusing the smtp.ini file is an obvious place for someone to look for and find the setting.

I also don't like `config.get('hide_received_header') === 'true';` comparing string values. That has a number of failure modes (especially in human expectations). We have robust boolean parsing already in the .ini file reader, which is another reason to put any boolean settings in ini files. If I merge this, I feel like I'm writing an IOU for future me to move this setting to smtp.ini, and then I have to also add backwards compatibility for it.

2020-11-04 05:31 UTC, adarshasp87 commented
> If this PR instead added settings to smtp.ini, I'd have merged it already.
> 
> I was hoping another core member would comment. I really dislike the "just add another config file" pattern for settings. It's terrible for discovery (if the config file doesn't exist, the only way to discover the setting is reading the code or docs. Perusing the smtp.ini file is an obvious place for someone to look for and find the setting.
> 
> I also don't like `config.get('hide_received_header') === 'true';` comparing string values. That has a number of failure modes (especially in human expectations). We have robust boolean parsing already in the .ini file reader, which is another reason to put any boolean settings in ini files. If I merge this, I feel like I'm writing an IOU for future me to move this setting to smtp.ini, and then I have to also add backwards compatibility for it.

2020-11-04 21:48 UTC, msimerson commented
@adarshasp87 , have a look at #2855

2020-11-06 04:57 UTC, adarshasp87 commented
@msimerson Thanks you so much for your support. Eagerly Looking for this feature getting released in new Haraka version

2020-11-06 05:00 UTC, msimerson commented
Go ahead and test drive #2855 for me.  Or wait until I get around to it..

2020-11-06 05:04 UTC, adarshasp87 commented
@msimerson Sure mate. I will post my findings soon

2020-11-17 05:19 UTC, closed without merging

2020-11-17 05:57 UTC, msimerson commented
@adarshasp87 , please post soon. I've been holding up a release pending your feedback. I'm planning to release Wednesday unless there's an issue.

2020-11-23 05:03 UTC, adarshasp87 commented
@msimerson My Apologies for the delayed response.  I have not observed any issues with the code.