dns: add dns.ini config file to set the default dns server list
haraka/Haraka pull request #2863
Opened 2020-11-19 01:19 UTC by gramakri

This feature is useful if you have dns servers running on a non-standard port. This is useful when running haraka in Docker. The base OS usually has systemd-resolved or equivalent which is a forwarding name server. In contrast, haraka ideally requires a recursive nameserver (for dnsbl to work, many OS default to google nameservers which zen spamhaus does not respond to).

Changes proposed in this pull request:
- This calls dns.setServers() on startup. Both master and child workers in a cluster will get the setting

Checklist:
- [X ] docs updated
- [ ] tests updated
- [X] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

2020-11-24 06:40 UTC, msimerson approved these changes
This looks fine to me. I have a couple general questions for @core. 

1. Should the load_dns_ini function should go in haraka-net-utils instead?
2. Instead of loading another config file, should this be in a `[dns_servers]` section of smtp.ini?

2020-12-01 11:39 UTC, smfreegard commented
> This looks fine to me. I have a couple general questions for @core.
> 
> 1. Should the load_dns_ini function should go in haraka-net-utils instead?

No - I don't think so.

> 2. Instead of loading another config file, should this be in a `[dns_servers]` section of smtp.ini?

Yes, should really should be in smtp.ini IMO, there's no need for a separate config file.   Because there's very little to configure here, `servers=` could probably just be `dns_servers=` and it can then live in `[main]`.

2020-12-01 18:00 UTC, gramakri commented
@smfreegard @msimerson OK, I will move it to a key named `dns_servers` in the main section.

2020-12-01 19:28 UTC, msimerson commented
>> 2. Instead of loading another config file, should this be in a `[dns_servers]` section of smtp.ini?
> Yes, should really should be in smtp.ini IMO, there's no need for a separate config file.   Because there's very little to configure here, `servers=` could probably just be `dns_servers=` and it can then live in `[main]`.

Might there be other dns settings in the future?  If there are, grouping them in a `dns` section would make sense. 

```ini
[dns]
servers=....
```

2020-12-03 00:23 UTC, msimerson requested changes
Switch status to changes pending.

2020-12-07 18:51 UTC, gramakri commented
Thanks for review but we found another way to workaround the DNS issue we had and we don't need this patch anymore. I will close this since I suspect it will bitrot if we don't use it!

2020-12-07 18:51 UTC, closed without merging

2020-12-07 20:25 UTC, msimerson commented
Glad you got the issue resolved. It'd be useful if you posted a brief summary of your workaround.

2020-12-07 21:26 UTC, msimerson commented
Should anyone want/need this in the future, a patch like this to Haraka would be welcome:

```diff
diff --git a/config/smtp.ini b/config/smtp.ini
index 0ebd21a4..e9f5888a 100644
--- a/config/smtp.ini
+++ b/config/smtp.ini
@@ -59,3 +62,7 @@ max_lines=1000
 
 ; replace max_received_count
 max_received=100
+
+[dns]
+; servers: a comma separated list of rfc5952 formatted addresses
+; servers=4.4.4.4,[2001:4860:4860::8888],4.4.4.4:1053,[2001:4860:4860::8888]:1053
diff --git a/server.js b/server.js
index a776130f..ffe8c993 100644
--- a/server.js
+++ b/server.js
@@ -102,6 +111,11 @@ Server.daemonize = function () {
     }
 }
 
+Server.configDNS = (servers) => {
+    try       { require('dns').setServers(servers.split(','));        }
+    catch (e) { logger.logerror(`Invalid DNS servers: ${e.message}`); }
+}
+
```

2020-12-07 22:36 UTC, gramakri commented
@msimerson The issue isn't Haraka related but very specific to our platform (cloudron).

But a brief summary is: on ubuntu 20, systemd-resolved is the default DNS server. That DNS server is non-recursive and thus queries to dnsbl like zen spamhaus may get blocked (on many VPS, it just forwards to Google DNS). We have Haraka deployed in container with dnsbl plugin. The dnsbl lookups fail because spamhaus blocks Google DNS. So, the fix was to use an additional unbound server. We couldn't run unbound on port 53 because systemd-resolved is there and thus I made this patch so that unbound runs on some other port and Haraka can then contact unbound for DNS. Sadly, this was causing other issues because /etc/resolv.conf cannot take a DNS port number and we have to then patch every software like this one :/ The fix was that we decided to disable systemd-resolved and replace it with unbound for all cloudron installations. This came with it's own set of headaches because of resolvconf but that is a story for another day!

2020-12-07 22:49 UTC, msimerson commented
Sounds like fun! Like pulling out ones fingernails. 😬 Instead of running a recursing resolver on another port, did you consider/try binding unbound to another IP?