Fix barelf URL
haraka/Haraka pull request #2957
Opened 2021-07-30 15:31 UTC by baudehlo

Fixes #2956

Changes proposed in this pull request:
- 
- 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

2021-07-31 04:02 UTC, sent commented
Hello @baudehlo,

Actually, it's not a problem with that exact URL, however with that domain https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/ 

Redirection works fine: https://haraka.github.io/barelf.html

Thanks!

2021-08-31 17:28 UTC, msimerson requested changes

2021-08-31 17:28 UTC, msimerson commented on connection.js
> +            this.respond(451, "Bare line-feed; see http://haraka.github.com/barelf/", () => {
```suggestion
            this.respond(451, "Bare line-feed; see http://haraka.github.io/barelf/", () => {
```

2021-09-09 21:06 UTC, merged

2023-08-03 20:38 UTC, christianflintrup commented
Seems the new URL (`http://haraka.github.io/barelf/`) also returns a 404 now.

2023-08-04 06:36 UTC, sent commented
> Seems the new URL (`http://haraka.github.io/barelf/`) also returns a 404 now.

Fixed in https://github.com/haraka/haraka.github.io/pull/43