allow configuring optional queue arguments
haraka/Haraka pull request #3239
Opened 2023-10-24 19:35 UTC by benjamonnguyen

Fixes #

Changes proposed in this pull request:
- Allow configuring optional queue arguments in queue/rabbitmq_amqplib plugin

Checklist:
- [x] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

2023-10-24 19:49 UTC, msimerson commented on plugins/queue/rabbitmq_amqplib.js
> +    const queueArgs = this.config.get("rabbitmq.ini").queue_args;
This could be shortened to:

```suggestion
    const queueArgs = cfg.queue_args;
```

or omit it entirely and reference it from cfg below.

2023-10-24 19:50 UTC, msimerson commented on plugins/queue/rabbitmq_amqplib.js
> +                    {durable, autoDelete, arguments: queueArgs},
```suggestion
                    {durable, autoDelete, arguments: cfg.queueArgs},
```

2023-10-24 19:52 UTC, msimerson requested changes
Shorten up the code per the inline comments. 

Also, not a bad idea to add a commented code block in rabbitmq_amqplib.ini with the available settings. That's often the first place an admin will go looking for knobs to twiddle.

2023-10-25 00:59 UTC, msimerson commented on plugins/queue/rabbitmq_amqplib.js
> +                    {durable, autoDelete, arguments: this.config.get("rabbitmq.ini").queue_args},
```suggestion
                    {durable, autoDelete, arguments: cfg.queue_args},
```

2023-10-25 00:59 UTC, benjamonnguyen commented
@msimerson `const cfg` is set to the [rabbitmq] section, but I've made the statement inline as suggested and added more documentation!

2023-10-25 01:02 UTC, msimerson approved these changes
LGTM

2023-10-25 04:35 UTC, merged