Fix startup race condition
haraka/Haraka pull request #3367
Opened 2024-05-21 17:27 UTC by analogic

Fixes #3366

Changes proposed in this pull request:
- making endpoint.bind() to async and awaiting in server.js

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

2024-05-21 17:34 UTC, msimerson commented
It looks like you also need to await [here](https://github.com/haraka/Haraka/pull/3367/files?diff=unified&w=1#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fL508)

2024-05-21 18:33 UTC, analogic commented
PR tested on multiple instances, seems OK
```
2024-05-21 20:25:39.085531500  [NOTICE] [-] [server] Listening on [::0]:25
2024-05-21 20:25:39.085777500  [NOTICE] [-] [server] Switching from current gid: 0
2024-05-21 20:25:39.086551500  [NOTICE] [-] [server] New gid: 8
2024-05-21 20:25:39.086589500  [NOTICE] [-] [server] Switching from current uid: 0
2024-05-21 20:25:39.087241500  [NOTICE] [-] [server] New uid: 88
```

2024-05-21 18:46 UTC, msimerson requested changes
LGTM.

I'd like to see one more change. Now that bind is async, I think we should be using `fs/promises` instead of sync calls:

```diff
diff --git a/endpoint.js b/endpoint.js
index 8154aef1..8f8e959a 100644
--- a/endpoint.js
+++ b/endpoint.js
@@ -1,7 +1,7 @@
 'use strict';
 // Socket address parser/formatter and server binding helper
 
-const fs = require('node:fs');
+const fs = require('node:fs/promises');
 const sockaddr = require('sockaddr');
 
 module.exports = function endpoint (addr, defaultPort) {
```

Since `fs.exists` has been deprecated for years, switch it to use `fs.access` or `fs.stat` before the `await fs.unlink(path);`

2024-05-21 18:54 UTC, msimerson commented
or [ignore errors](https://nodejs.org/api/fs.html#fspromisesrmpath-options) when the file doesn't exist:

```js
await fs.rm(this.path, { force: true });
```

2024-05-21 18:55 UTC, msimerson commented on endpoint.js
> +        return await new Promise((resolve, reject) => {
```suggestion
        return new Promise((resolve, reject) => {
```

There's no need to await here.

2024-05-22 06:39 UTC, analogic commented
When I "grep node:fs" I didn't find many "promises" so I assumed it would be better not to change. I chose "rm" for simplicity...

2024-05-22 14:22 UTC, msimerson approved these changes

2024-05-22 14:22 UTC, merged

2024-05-22 14:23 UTC, msimerson commented
Thanks! Great job on the diagnosis and the fix.